In [6]:
import numpy as np
import pandas as pd

In [7]:
A = np.array([[3,  2, -1],
              [3, -2,  0],
              [3,  2,  1],
              [3, -2,  0],
              [3,  2, -1]])

In [8]:
num_filas, num_columnas = A.shape
Q = np.zeros((num_filas, num_columnas))  # Initialize Q matrix to store normalized columns
R = np.zeros((num_columnas, num_columnas))  # Initialize R matrix

for i in range(num_columnas):
    column = A[:, i].astype(float)  # Convert to float to ensure consistent data type

    # Orthogonalize the column with respect to previous columns
    for j in range(i):
        projection = np.dot(Q[:, j], column)
        R[j, i] = projection  # Store the projection in the R matrix
        column -= projection * Q[:, j]

    # Normalize the column
    column_norm = np.linalg.norm(column, ord=2)
    Q[:, i] = column / column_norm
    R[i, i] = column_norm  # Diagonal elements of R matrix

print("Matrix Q (columns normalized):")
print(Q)

print("\nMatrix R:")
print(R)


Matrix Q (columns normalized):
[[ 0.4472136   0.36514837 -0.40824829]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837  0.81649658]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837 -0.40824829]]

Matrix R:
[[ 6.70820393  0.89442719 -0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.          1.63299316]]


# 2

In [9]:
df = pd.read_csv("BTC-USD.csv")
data = df[["Open","High","Close","Low","Volume"]]
data.head()

Open        High       Close         Low    Volume
0  465.864014  468.174011  457.334015  452.421997  21056800
1  456.859985  456.859985  424.440002  413.104004  34483200
2  424.102997  427.834991  394.795990  384.532013  37919700
3  394.673004  423.295990  408.903992  389.882996  36863600
4  408.084991  412.425995  398.821014  393.181000  26580100

In [10]:
x = data.drop("Open", axis=1)
data["intercepto"] = 1
data

/tmp/ipykernel_1180/609795845.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["intercepto"] = 1


Open          High         Close           Low       Volume  \
0       465.864014    468.174011    457.334015    452.421997     21056800   
1       456.859985    456.859985    424.440002    413.104004     34483200   
2       424.102997    427.834991    394.795990    384.532013     37919700   
3       394.673004    423.295990    408.903992    389.882996     36863600   
4       408.084991    412.425995    398.821014    393.181000     26580100   
...            ...           ...           ...           ...          ...   
2742  41246.132813  41454.410156  41077.996094  40668.042969  24615543271   
2743  41074.105469  43124.707031  42358.808594  40948.281250  32004652376   
2744  42364.378906  42893.507813  42892.957031  41877.507813  25242943069   
2745  42886.652344  44131.855469  43960.933594  42726.164063  31042992291   
2746  43958.675781  44982.519531  44395.964844  43711.871094  30379415552   

      intercepto  
0              1  
1              1  
2              1  
3              1  
4              1  
...          ...  
2742           1  
2743           1  
2744           1  
2745           1  
2746           1  

[2747 rows x 6 columns]