In [223]:
import numpy as np
import scipy.linalg as sla
from scipy.linalg import eig

# Power method

In [224]:
def power_method(A, X, tolerance=0.0001, max_iterations=200):
    m = 0
    difference = X
    while m < max_iterations and np.linalg.norm(difference) > tolerance:
        X_previous = X
        X = A @ X
        X = X / np.linalg.norm(X)
        difference = X - X_previous
        m += 1
    eigenvalue = np.linalg.norm(A @ X)
    print("Eigenvector corresponding to biggest eigenvalue is approximately:")
    print(X, "\n")
    print("Magnitude of the biggest eigenvalue is approximately:")
    print(eigenvalue, "\n")
    return eigenvalue, X

# Inverse power method

In [225]:
def inverse_power_method(A, X, tolerance=0.0001, max_iterations=200):
    m = 0
    difference = X
    LU_factorization = sla.lu_factor(A)

    while m < max_iterations and np.linalg.norm(difference) > tolerance:
        X_previous = X
        X = sla.lu_solve(LU_factorization, X)
        X = X / np.linalg.norm(X)
        difference = X - X_previous
        m = m + 1

    eigenvalue = np.linalg.norm(A @ X)
    print("Eigenvector corresponding to smallest eignvalue is approximately:")
    print(X, "\n")
    print("Magnitude of the smallest eigenvalue of A is approximately:")
    print(eigenvalue, "\n")
    return eigenvalue, X

# Shifted inverse power method

In [226]:
def shifted_inverse_power_method(A, X, mu=None, tolerance=0.0001, max_iterations=200):
    m = 0
    difference = X
    I = np.eye(len(A))
    if not mu:
        max_eigenvalue, _ = power_method(A, X)
        min_eigenvalue, _ = inverse_power_method(A, X)
        mu = np.average([max_eigenvalue, min_eigenvalue])
    Shifted_A = A - mu * I
    LU_factorization = sla.lu_factor(Shifted_A)

    while m < max_iterations and np.linalg.norm(difference) > tolerance:
        X_previous = X
        X = sla.lu_solve(LU_factorization, X)
        X = X / np.linalg.norm(X)

        ## Compute difference in stopping condition
        difference = X - X_previous

        m = m + 1
    eigenvalue = np.linalg.norm(A @ X)
    print("Eigenvector is approximately:")
    print(X, "\n")
    print("Eigenvalue of A is approximately:")
    print(eigenvalue)
    return eigenvalue, X

# Ejercicios

Exercise 1: Let A
 be the matrix from the Inverse Power Method example.

(a) Use the Power Method to approximate the largest eigenvalue λ1
. Verify that the exact value of λ1 is 12.

In [227]:
A = np.array([[9, -1, -3], [0, 6, 0], [-6, 3, 6]])
X = np.array([1, 0, 0])
power_method(A, X, tolerance=0.0001, max_iterations=200)

Eigenvector corresponding to biggest eigenvalue is approximately:
[ 0.70711487  0.         -0.70709869] 

Magnitude of the biggest eigenvalue is approximately:
12.000034331669662 



(12.000034331669662, array([ 0.70711487,  0.        , -0.70709869]))

(b) Apply the Inverse Power Method with a shift of μ=10. Explain why the results differ from those in the example.

In [228]:
A = np.array([[9, -1, -3], [0, 6, 0], [-6, 3, 6]])
X = np.array([0, 1, 0])
shifted_inverse_power_method(A, X, mu=10, tolerance=0.0001, max_iterations=200)

Eigenvector is approximately:
[-7.07113254e-01 -1.94211789e-05  7.07100308e-01] 

Eigenvalue of A is approximately:
11.999972530202639


(11.999972530202639,
 array([-7.07113254e-01, -1.94211789e-05,  7.07100308e-01]))

El resultado es diferente al ejemplo con un Mu que se aleja de la mitad del eigenvalue minimo y maximo, por lo tanto me acerco al eigen value maximo.

(c) Apply the Inverse Power Method with a shift of 𝜇=7.5
 and the initial vector given below. Explain why the sequence of vectors approach the eigenvector corresponding to 𝜆1

In [229]:
A = np.array([[9, -1, -3], [0, 6, 0], [-6, 3, 6]])
X = np.array([1, 0, 0])
shifted_inverse_power_method(A, X, mu=7.5, tolerance=0.000001, max_iterations=1000)

Eigenvector is approximately:
[ 1. -0. -0.] 

Eigenvalue of A is approximately:
10.816653826391969


(10.816653826391969, array([ 1., -0., -0.]))

Lo que pasa no es que se acerque al eigen value máximo, sino que el método no converge con este vector en particular. Si se cambia el vector inicial, el método converge.

### Exercise 2:
Let B be the following matrix.

(a) Apply the Power Method and Inverse Power Method with shifts to approximate all eigenvalues of the matrix B. (Note that one of the eigenvalues of this matrix is negative.)

In [231]:
A = np.array([[-2, -18, 6], [-11, 3, 11], [-27, 15, 31]])
X = np.array([0, 1, 0])

In [232]:
inverse_power_method(A, X, tolerance=0.0001, max_iterations=200)

Eigenvector corresponding to smallest eignvalue is approximately:
[-7.07095991e-01  2.15801743e-05 -7.07117571e-01] 

Magnitude of the smallest eigenvalue of A is approximately:
4.000549345743139 



(4.000549345743139, array([-7.07095991e-01,  2.15801743e-05, -7.07117571e-01]))

In [233]:
power_method(A, X, tolerance=0.0001, max_iterations=200)

Eigenvector corresponding to biggest eigenvalue is approximately:
[1.12395332e-05 3.16231164e-01 9.48682165e-01] 

Magnitude of the biggest eigenvalue is approximately:
35.999687334908465 



(35.999687334908465, array([1.12395332e-05, 3.16231164e-01, 9.48682165e-01]))

In [234]:
shifted_inverse_power_method(A, X, mu=None, tolerance=0.000001, max_iterations=1000)

Eigenvector corresponding to biggest eigenvalue is approximately:
[1.12395332e-05 3.16231164e-01 9.48682165e-01] 

Magnitude of the biggest eigenvalue is approximately:
35.999687334908465 

Eigenvector corresponding to smallest eignvalue is approximately:
[-7.07095991e-01  2.15801743e-05 -7.07117571e-01] 

Magnitude of the smallest eigenvalue of A is approximately:
4.000549345743139 

Eigenvector is approximately:
[-0.88693195  0.15002491 -0.43685723] 

Eigenvalue of A is approximately:
14.2092972315023


(14.2092972315023, array([-0.88693195,  0.15002491, -0.43685723]))

(b) Check your results using the eig function in SciPy.

In [235]:
# Calcula los valores y vectores propios de la matriz original
valores_propios_original, vectores_propios_original = eig(A)
print(f"Valores propios de la matriz original:\n {valores_propios_original}")
print(f"Vectores propios de la matriz original:\n {vectores_propios_original}")

# Calcula los valores y vectores propios de la matriz inversa
valores_propios_inversa, vectores_propios_inversa = eig(np.linalg.inv(A))
print(f"Valores propios de la matriz inversa:\n {valores_propios_inversa}")
print(f"Vectores propios de la matriz inversa:\n {vectores_propios_inversa}")

Valores propios de la matriz original:
 [36.+0.j -8.+0.j  4.+0.j]
Vectores propios de la matriz original:
 [[ 1.02854624e-17 -8.16496581e-01  7.07106781e-01]
 [-3.16227766e-01 -4.08248290e-01  1.89360275e-16]
 [-9.48683298e-01 -4.08248290e-01  7.07106781e-01]]
Valores propios de la matriz inversa:
 [ 0.25      +0.j -0.125     +0.j  0.02777778+0.j]
Vectores propios de la matriz inversa:
 [[ 7.07106781e-01 -8.16496581e-01  4.90321070e-16]
 [-2.27036279e-17 -4.08248290e-01  3.16227766e-01]
 [ 7.07106781e-01 -4.08248290e-01  9.48683298e-01]]
