In [81]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [82]:
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for j in range(n):
        v = A[:, j]
        W = v
        for i in range(j):
            W = W - (np.dot(v, Q[:, i])) * Q[:, i]
        norm_W = np.linalg.norm(W)
        Q[:, j] = W / norm_W
        for i in range(j):
            R[i][j] = np.dot(v, Q[:, i])
        R[j][j] = norm_W
    return Q, R

In [83]:
A = np.array([[3,2,-1], [3,-2,0], [3,2,1], [3,-2,0], [3,2,-1]])

In [84]:
A.shape

(5, 3)

In [85]:
Q, R = gram_schmidt(A)

In [86]:
Q.shape

(5, 3)

In [87]:
Q

array([[ 4.47213595e-01,  3.65148372e-01, -4.08248290e-01],
       [ 4.47213595e-01, -5.47722558e-01, -3.39934989e-17],
       [ 4.47213595e-01,  3.65148372e-01,  8.16496581e-01],
       [ 4.47213595e-01, -5.47722558e-01, -3.39934989e-17],
       [ 4.47213595e-01,  3.65148372e-01, -4.08248290e-01]])

In [88]:
R.shape

(3, 3)

In [89]:
R

array([[ 6.70820393,  0.89442719, -0.4472136 ],
       [ 0.        ,  4.38178046, -0.36514837],
       [ 0.        ,  0.        ,  1.63299316]])

In [90]:
Q @ R

array([[ 3.00000000e+00,  2.00000000e+00, -1.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00,  3.57852865e-18],
       [ 3.00000000e+00,  2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00,  3.57852865e-18],
       [ 3.00000000e+00,  2.00000000e+00, -1.00000000e+00]])

In [91]:
X = np.random.rand(100, 3)
X = np.concatenate((np.ones((100, 1)), X), axis=1)
y = np.random.rand(100, 1)

In [92]:
X

array([[1.        , 0.43210772, 0.22907838, 0.33926115],
       [1.        , 0.35772055, 0.86552468, 0.97715054],
       [1.        , 0.31668179, 0.27970237, 0.68488026],
       [1.        , 0.75969226, 0.30080792, 0.05757154],
       [1.        , 0.70815257, 0.49729129, 0.08537185],
       [1.        , 0.60928941, 0.2612134 , 0.89818382],
       [1.        , 0.98785301, 0.26245901, 0.69153359],
       [1.        , 0.03052967, 0.78917928, 0.33462088],
       [1.        , 0.40219741, 0.65114805, 0.64935519],
       [1.        , 0.63283111, 0.48416841, 0.94896714],
       [1.        , 0.08749577, 0.71782406, 0.88910236],
       [1.        , 0.40480698, 0.69136437, 0.08240118],
       [1.        , 0.75660002, 0.90668603, 0.14534105],
       [1.        , 0.65026081, 0.58809508, 0.85016943],
       [1.        , 0.88790507, 0.83029955, 0.95594516],
       [1.        , 0.20748799, 0.84497965, 0.96898539],
       [1.        , 0.27242422, 0.74652512, 0.77750049],
       [1.        , 0.46570041,

In [93]:
y

array([[0.53813806],
       [0.81354196],
       [0.2291541 ],
       [0.86094494],
       [0.69062023],
       [0.26823164],
       [0.38629082],
       [0.57956655],
       [0.46228769],
       [0.98805924],
       [0.91161329],
       [0.67937536],
       [0.47703401],
       [0.92003042],
       [0.08693509],
       [0.87634685],
       [0.79900322],
       [0.62308819],
       [0.01826006],
       [0.34716994],
       [0.19405874],
       [0.18219952],
       [0.79847638],
       [0.05078322],
       [0.05632622],
       [0.56898833],
       [0.42014797],
       [0.75736141],
       [0.3452951 ],
       [0.18892087],
       [0.62490158],
       [0.03313483],
       [0.06185156],
       [0.72692595],
       [0.63038375],
       [0.00107625],
       [0.22608866],
       [0.79061636],
       [0.38161623],
       [0.53547294],
       [0.43102083],
       [0.14047256],
       [0.68595238],
       [0.37415762],
       [0.2084379 ],
       [0.60150986],
       [0.88897103],
       [0.814

In [94]:
Q, R = gram_schmidt(X)

In [95]:
m, n = Q.shape

In [96]:
b = Q.T @ y

In [97]:
def backward_substitution(U, b):
    n = len(b)
    x = np.zeros_like(b)
    
    for i in range(n - 1, -1, -1):
        sum_j = sum(U[i,j] * x[j] for j in range(i + 1, n))
        x[i] = (b[i] - sum_j) / U[i,i]

    return x

In [98]:
backward_substitution(np.array([[1, 2], [0, 2]]), np.array([5, 6]))

array([-1,  3])

In [99]:
coefficients = backward_substitution(R, b)

In [100]:
coefficients

array([[ 0.59254515],
       [-0.24007033],
       [-0.06637677],
       [ 0.08290641]])

In [101]:
lr = LinearRegression(fit_intercept=False)
lr.fit(X, y)
lr.coef_

array([[ 0.59254515, -0.24007033, -0.06637677,  0.08290641]])