In [2]:
import numpy as np
import scipy

A) Implemente un algoritmo para calcular la factorización QR de una
matríz basando en el proceso de ortogonalización de Grahm-Schmidt.
El algoritmo debe recibir una matriz A de tamaño m × n con m ≥ n
y retornar una matriz Q de tamaño m × n y una matriz triangular
superior R de tamaño n×n, tales que QtQ = In y A = QR. Compare
los resultados de su algoritmo con los de la función scipy.linalg.qr.

In [3]:
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        W = v
        for i in range(j):
            W = W - (np.dot(v, Q[:, i])) * Q[:, i]
        norm_W = np.linalg.norm(W)
        Q[:, j] = W / norm_W
        for i in range(j):
            R[i][j] = np.dot(v, Q[:, i])
        R[j][j] = norm_W
    return Q, R

B) ¿Que pasa con la factorización QR cuando las columnas son linealmente
dependientes?

In [4]:
A = np.array([[1, 1, 1], [2, 2, 2], [1, 6, 7]]).T
A

array([[1, 2, 1],
       [1, 2, 6],
       [1, 2, 7]])

In [5]:
Q, R = gram_schmidt(A)
print(f"Q: {Q}")
print(f"R: {R}")

Q: [[ 0.57735027 -0.57735027 -0.89860644]
 [ 0.57735027 -0.57735027 -0.35944258]
 [ 0.57735027 -0.57735027 -0.2516098 ]]
R: [[ 1.73205081e+00  3.46410162e+00  8.08290377e+00]
 [ 0.00000000e+00  7.69185075e-16 -8.08290377e+00]
 [ 0.00000000e+00  0.00000000e+00  9.27361850e+00]]


In [6]:
print(Q[:, 0] @ Q[:, 1])
print(Q[:, 0] @ Q[:, 2])
print(Q[:, 1] @ Q[:, 2])

-1.0000000000000002
-0.8716019289105668
0.8716019289105668


In [7]:
Q.T @ Q

array([[ 1.        , -1.        , -0.87160193],
       [-1.        ,  1.        ,  0.87160193],
       [-0.87160193,  0.87160193,  1.        ]])

Cuando hay columnas que son combinaciones lineales de otras, es decir, las columnas de la matriz no son linealmente independientes, entonces ocurren varias cosas:

1) Las columnas de la matriz Q, no son ortogonales
2) Por lo tanto, Q.T * Q no es igual a la matriz identidad
3) Notamos que R sigue siendo una matriz triangular superior, pero tiene ceros en la diagonal, por lo tanto no es una matriz invertible y tiene determinante igual a cero.
4) La factorización ya no es única

C) Averigüe bajo cuales condiciones la factorización QR es única.

La factorización es única cuando las columnas de la matriz A son linealmente independientes.

Probamos encontrar A a partir de Q*R

In [8]:
Q @ R

array([[1., 2., 1.],
       [1., 2., 6.],
       [1., 2., 7.]])

# Haciendo cálculo con otras matrices:

In [9]:
A = np.array([[3, 2, -1], [3, -2, 0], [3, 2, 1], [3, -2, 0], [3, 2, -1]])
A

array([[ 3,  2, -1],
       [ 3, -2,  0],
       [ 3,  2,  1],
       [ 3, -2,  0],
       [ 3,  2, -1]])

In [10]:
Q, R = gram_schmidt(A)
print(f"Q: {Q}")
print(f"R: {R}")

Q: [[ 0.4472136   0.36514837 -0.40824829]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837  0.81649658]
 [ 0.4472136  -0.54772256  0.        ]
 [ 0.4472136   0.36514837 -0.40824829]]
R: [[ 6.70820393  0.89442719 -0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.          1.63299316]]


In [11]:
(Q.T @ Q).round()

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])

In [12]:
(Q @ R).round()

array([[ 3.,  2., -1.],
       [ 3., -2., -0.],
       [ 3.,  2.,  1.],
       [ 3., -2., -0.],
       [ 3.,  2., -1.]])

In [16]:
Q_s, R_s = scipy.linalg.qr(A, mode="economic")
print(f"Q:\n {Q_s}")
print(f"Shape of Q: {Q_s.shape}")
print(f"R:\n {R_s}")
print(f"Shape of R: {R_s.shape}")

Q:
 [[-4.47213595e-01  3.65148372e-01  4.08248290e-01]
 [-4.47213595e-01 -5.47722558e-01 -5.55111512e-17]
 [-4.47213595e-01  3.65148372e-01 -8.16496581e-01]
 [-4.47213595e-01 -5.47722558e-01 -2.77555756e-17]
 [-4.47213595e-01  3.65148372e-01  4.08248290e-01]]
Shape of Q: (5, 3)
R:
 [[-6.70820393 -0.89442719  0.4472136 ]
 [ 0.          4.38178046 -0.36514837]
 [ 0.          0.         -1.63299316]]
Shape of R: (3, 3)


In [17]:
(Q_s.T @ Q_s).round()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
print(Q_s @ R_s)

[[ 3.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [ 3.00000000e+00 -2.00000000e+00  1.34305839e-16]
 [ 3.00000000e+00  2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -2.00000000e+00  1.29520787e-16]
 [ 3.00000000e+00  2.00000000e+00 -1.00000000e+00]]
