In [81]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [82]:
def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for j in range(n):
        v = A[:, j]
        W = v
        for i in range(j):
            W = W - (np.dot(v, Q[:, i])) * Q[:, i]
        norm_W = np.linalg.norm(W)
        Q[:, j] = W / norm_W
        for i in range(j):
            R[i][j] = np.dot(v, Q[:, i])
        R[j][j] = norm_W
    return Q, R

In [83]:
A = np.array([[3,2,-1], [3,-2,0], [3,2,1], [3,-2,0], [3,2,-1]])

In [85]:
Q, R = gram_schmidt(A)

In [87]:
Q

array([[ 4.47213595e-01,  3.65148372e-01, -4.08248290e-01],
       [ 4.47213595e-01, -5.47722558e-01, -3.39934989e-17],
       [ 4.47213595e-01,  3.65148372e-01,  8.16496581e-01],
       [ 4.47213595e-01, -5.47722558e-01, -3.39934989e-17],
       [ 4.47213595e-01,  3.65148372e-01, -4.08248290e-01]])

In [89]:
R

array([[ 6.70820393,  0.89442719, -0.4472136 ],
       [ 0.        ,  4.38178046, -0.36514837],
       [ 0.        ,  0.        ,  1.63299316]])

In [91]:
X = np.random.rand(100, 3)
X = np.concatenate((np.ones((100, 1)), X), axis=1)
y = np.random.rand(100, 1)

In [94]:
Q, R = gram_schmidt(X)

In [95]:
m, n = Q.shape

In [96]:
b = Q.T @ y

In [97]:
def backward_substitution(U, b):
    n = len(b)
    x = np.zeros_like(b)
    
    for i in range(n - 1, -1, -1):
        sum_j = sum(U[i,j] * x[j] for j in range(i + 1, n))
        x[i] = (b[i] - sum_j) / U[i,i]

    return x

In [98]:
backward_substitution(np.array([[1, 2], [0, 2]]), np.array([5, 6]))

array([-1,  3])

In [99]:
coefficients = backward_substitution(R, b)

In [100]:
coefficients

array([[ 0.59254515],
       [-0.24007033],
       [-0.06637677],
       [ 0.08290641]])

In [101]:
lr = LinearRegression(fit_intercept=False)
lr.fit(X, y)
lr.coef_

array([[ 0.59254515, -0.24007033, -0.06637677,  0.08290641]])